apiVersion: batch/v1
kind: Job
metadata:
  name: sun3ah-sun3ah-cache-job
  namespace: sun3ah
spec:
  backoffLimit: 6
  completionMode: NonIndexed
  completions: 1
  parallelism: 1
  suspend: false
  template:
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - php artisan cache:clear && php artisan config:clear && php artisan view:clear && php artisan route:clear
        env:
        - name: DB_CONNECTION
          valueFrom:
            secretKeyRef:
              key: DB_CONNECTION
              name: database-credentials
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              key: DB_HOST
              name: database-credentials
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              key: DB_PORT
              name: database-credentials
        - name: DB_DATABASE
          valueFrom:
            secretKeyRef:
              key: DB_DATABASE
              name: database-credentials
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              key: DB_USERNAME
              name: database-credentials
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: DB_PASSWORD
              name: database-credentials
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: redis-credentials
              key: REDIS_HOST
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-credentials
              key: REDIS_PASSWORD
        - name: REDIS_PORT
          valueFrom:
            secretKeyRef:
              name: redis-credentials
              key: REDIS_PORT
        image: <IMAGE_PLACEHOLDER>
        imagePullPolicy: IfNotPresent
        name: cache
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
